const data = [
    {
        id:1,
        img:"images/black-friday-sale-decoration-background-with-shopping-trolley-copy-space_257995-187.webp",
        title:'SUMMER SALE',
        desc:"DONT CONPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVAL",
        bg:"f5fafd"
    },

    {
        id:2,
        img:"images/R (1).png",
        title:'AUTOMINE COLLECTION',
        desc:"DONT CONPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVAL",
        bg:"fcf1ed"
    },

    {
        id:3,
        img:"images/black-friday-sale-decoration-background-with-shopping-trolley-copy-space_257995-187.webp",
        title:'WINTER',
        desc:"DONT CONPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVAL",
        bg:"f5fafd"
    }
]
export default data